This file contains some code that I was using to test out feature selection methods


```{r, echo = FALSE}
# VARIABLES REMOVED
#  1-S.Walking.Distractions.Pull_prod,
#  2-S.Crate.Stimulus_mean,
#  Tea.Towel.First.Response..Attempts.to.Removes.towel.with.mouth. -> INTERACTION WITH BREED
#  3-Tea.Towel.First.Response..Indifferent.Yes 
#  S.Sociability_mean, -> INTERACTION WITH INTERCEPT
#  4-Body.check.General..Licks.
```

```{r, echo = FALSE}
# multivariate model 1
glm_1 <- glm(Outcome ~ ., data=data_1, family = binomial(link = logit))
summary(glm_1)
model_1 <- data.frame(tidy(glm_1), row.names = 1)
model_1 %>% arrange(desc(p.value)) %>% select(estimate, p.value)

glm_old <- glm_new
data_new <- data_1 %>% select(-S.Walking.Distractions.Pull_prod, -S.Crate.Stimulus_mean, 
        -Tea.Towel.First.Response..Attempts.to.Removes.towel.with.mouth., -Tea.Towel.First.Response..Indifferent., 
        -S.Sociability_mean, -Body.check.General..Licks., -Breed, )
glm_new <- glm(Outcome ~ ., data=data_new, family = binomial(link = logit))
glm_old$deviance
glm_new$deviance
lrtest(glm_old, glm_new)
model_new <- data.frame(tidy(glm_new), row.names = 1)
model_new %>% arrange(desc(p.value)) %>% select(estimate, p.value)

```


```{r, echo = FALSE}
# variable to remove 1
print("Remove S.Walking.Distractions.Pull_prod")
data_2 <- data_1 %>% select(-S.Walking.Distractions.Pull_prod)

# multivariate model 2
glm_2 <- glm(Outcome ~ ., data=data_2, family = binomial(link = logit))
summary(glm_2)
model_2 <- data.frame(tidy(glm_2), row.names = 1)
# condition 1 
lrtest(glm_1, glm_2)
# condition 2
model_12 <- cbind(model_1 %>% select(estimate) %>% filter(row.names(model_1) != "S.Walking.Distractions.Pull_prod"), 
                model_2 %>% select(estimate))
colnames(model_12) <- c("estimate.1", "estimate.2")
model_12$difference <- round((model_12$estimate.2 - model_12$estimate.1) / model_12$estimate.1, 2)
model_12 %>% filter(difference > 0.2 | difference < - 0.2 )
```

```{r, echo = FALSE}
# variable to remove 2
model_2 %>% arrange(desc(p.value)) %>% select(estimate, p.value)
print("Remove S.Crate.Stimulus_mean")
data_3 <- data_2 %>% select(-S.Crate.Stimulus_mean)

# multivariate model 3
glm_3 <- glm(Outcome ~ ., data=data_3, family = binomial(link = logit))
summary(glm_3)
model_3 <- data.frame(tidy(glm_3), row.names = 1)

# condition 1: I can't compare them because more examples were added to the models
lrtest(glm_2, glm_3)
glm_3$df.residual
# condition 2
model_23 <- cbind(model_2 %>% select(estimate) %>% filter(row.names(model_2) != "S.Crate.Stimulus_mean"), 
                model_3 %>% select(estimate))
colnames(model_23) <- c("estimate.2", "estimate.3")
model_23$difference <- round((model_23$estimate.3 - model_23$estimate.2) / model_23$estimate.2, 4)
model_23 %>% filter(difference > 0.2 | difference < - 0.2 )

```


```{r, echo = FALSE}
# variable to remove 3
model_3 %>% arrange(desc(p.value)) %>% select(estimate, p.value)
print("Remove Tea.Towel.First.Response..Attempts.to.Removes.towel.with.mouth.")
data_4 <- data_3 %>% select(-Tea.Towel.First.Response..Attempts.to.Removes.towel.with.mouth.)

# multivariate model 4
glm_4 <- glm(Outcome ~ ., data=data_4, family = binomial(link = logit))
summary(glm_4)
model_4 <- data.frame(tidy(glm_4), row.names = 1)

# condition 1
lrtest(glm_3, glm_4)
# condition 2: RED FLAG >20% CHANGE WITH BREED -> 
model_34 <- cbind(model_3 %>% select(estimate) %>% filter(row.names(model_3) != "Tea.Towel.First.Response..Attempts.to.Removes.towel.with.mouth.Yes"), 
                model_4 %>% select(estimate))
colnames(model_34) <- c("estimate.3", "estimate.4")
model_34$difference <- round((model_34$estimate.4 - model_34$estimate.3) / model_34$estimate.3, 4)
model_34 %>% filter(difference > 0.2 | difference < - 0.2 )
print("CAN NOT REMOVE Tea.Towel.First.Response..Attempts.to.Removes.towel.with.mouth.)
```

```{r, echo = FALSE}
# variable to remove 5
model_3 %>% arrange(desc(p.value)) %>% select(estimate, p.value)
data_5 <- data_3 %>% select(-Tea.Towel.First.Response..Indifferent.)

# multivariate model 5
glm_5 <- glm(Outcome ~ ., data=data_5, family = binomial(link = logit))
summary(glm_5)
model_5 <- data.frame(tidy(glm_5), row.names = 1)

# condition 1: OK
lrtest(glm_3, glm_5)
# condition 2: OK
model_35 <- cbind(model_3 %>% select(estimate) %>% filter(row.names(model_3) != "Tea.Towel.First.Response..Indifferent.Yes"), 
                model_5 %>% select(estimate))
colnames(model_35) <- c("estimate.4", "estimate.5")
model_35$difference <- round((model_45$estimate.5 - model_45$estimate.4) / model_45$estimate.4, 4)
model_35 %>% filter(difference > 0.2 | difference < - 0.2 )

```


```{r, echo = FALSE}
# variable to remove 6
model_5 %>% arrange(desc(p.value)) %>% select(estimate, p.value)
data_6 <- data_5 %>% select(-S.Sociability_mean)

# multivariate model 6
glm_6 <- glm(Outcome ~ ., data=data_6, family = binomial(link = logit))
summary(glm_6)
model_6 <- data.frame(tidy(glm_6), row.names = 1)

# condition 1: OK
lrtest(glm_5, glm_6)
# condition 2: NOT OKAY, INTERCEPT 40% DEVIANCE
model_56 <- cbind(model_5 %>% select(estimate) %>% filter(row.names(model_5) != "S.Sociability_mean"), 
                model_6 %>% select(estimate))
colnames(model_56) <- c("estimate.5", "estimate.6")
model_56$difference <- round((model_56$estimate.6 - model_56$estimate.5) / model_56$estimate.5, 4)
model_56 %>% filter(difference > 0.2 | difference < - 0.2 )
```

```{r, echo = FALSE}
# variable to remove 7
model_5 %>% arrange(desc(p.value)) %>% select(estimate, p.value)
data_7 <- data_5 %>% select(-Breed)

# multivariate model 6
glm_7 <- glm(Outcome ~ ., data=data_7, family = binomial(link = logit))
summary(glm_7)
model_7 <- data.frame(tidy(glm_7), row.names = 1)

# condition 1: OK
lrtest(glm_5, glm_7)
# condition 2: NOT OKAY, INTERCEPT 40% DEVIANCE
model_57 <- cbind(model_5 %>% select(estimate) %>% filter(row.names(model_5) != "S.Sociability_mean"), 
                model_7 %>% select(estimate))
colnames(model_57) <- c("estimate.5", "estimate.7")
model_57$difference <- round((model_57$estimate.7 - model_57$estimate.5) / model_57$estimate.5, 4)
model_57 %>% filter(difference > 0.2 | difference < - 0.2 )
```
