I created this example to double check if R really predicts the probability of the factor that appears in second [0 1], so the probability of 1
Source: https://towardsdatascience.com/implementing-binary-logistic-regression-in-r-7d802a9d98fe

```{r, echo = FALSE}
install.packages('mlbench')
install.packages('MASS')
install.packages('pROC')
library(mlbench)
library(MASS)
library(pROC)
data(PimaIndiansDiabetes2)
head(PimaIndiansDiabetes2)
newdata <- na.omit(PimaIndiansDiabetes2)
summary(newdata)

```

```{r, echo = FALSE}
newdata$age_bucket <- as.factor(ifelse(newdata$age<=30,"20-30",ifelse(newdata$age<=40,"31-40",ifelse(newdata$age<=50,"41-50","50+"))))
newdata$preg_bucket <- as.factor(ifelse(newdata$pregnant<=5,"0–5",ifelse(newdata$pregnant<=10,"6–10","10+")))
newdata2 <- newdata[,c("diabetes","glucose","pressure","triceps","insulin","mass","pedigree","age_bucket","preg_bucket")]
```

```{r, echo = FALSE}
logit_1 <- glm(diabetes~., family = binomial, data = newdata2)
newdata$diabetes

summary(logit_1)
pred_prob <- predict(logit_1, type = "response")
pred_class <- ifelse(pred_prob, "pos", "neg")

```